### ISSUE TITLE
Handling of un-registered contentTypes

### ISSUE THREAD

**Issue by wsmckenz** [RIAEvangelist/node-http-server#12]
Is it possible to handle unknown contentTypes better. Right now it throws an exception if an unknown content type is requested. Would be better to ignore it and return not found?

    _http_outgoing.js:329
        throw new Error('`value` required in setHeader("' + name + '", value).');
        ^

    Error: `value` required in setHeader("Content-Type", value).
         at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:329:11)
         at Server.<anonymous> (g:\work\energistics\energyml\tools\etp-sample-js\node_modules\node-http-server\server\http.js:155:22)
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by RIAEvangelist** [comment]
Is your repo public?

node-http-server gives a 404 for unknown content types I believe.

**Comment by wsmckenz** [comment]
My repo is public but it pretty big with a bunch of dependencies to get it started. It's at https://bitbucket.org/energistics/etp-sample-js

However, I can reproduce with the following:

     npm install node-http-server

**server.js:**

     var path=require('path');
     var webserver = require('node-http-server');
     var serverConfig = new webserver.Config;

     serverConfig.port = 8080;
     serverConfig.root = path.dirname(module.filename);
     //serverConfig.contentType.xml = "text/xml";

     webserver.deploy(serverConfig);

**test.xml:**

     <foo>bar</foo>

Without the xml contentType, it throws, as described above. The lookup of the contentType at line 155 of http.js will produce a null, and that then causes it to throw when trying to set the header. Might be a version thing for node's http library. I'm on v4.1.1 of Node.

It could also be fixed by just providing a default contentType is nothing is found, but that might be a security risk.

**Comment by RIAEvangelist** [comment]
Legit.

Would you like to do a fix and PR? I know not everyone has time, so I thought I would ask since you identified it. ***If not, I or @MaybeRex will gladly fix it***

Thanks for the leg work in identifying and reporting.

**Comment by RIAEvangelist** [comment]
Thanks for the fix! It is very appreciated.

:+1:
