### ISSUE TITLE
Enabling CORS (setting response headers)

### ISSUE THREAD

**Issue by OlleMattsson** [RIAEvangelist/node-http-server#15]
Is there a built in way to  set  CORS headers when using this package?

EDIT: More specifically, how should one go about setting the response header
`Access-Control-Allow-Origin: *`
`Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept`

In ExpressJS it is achieved like described here: http://enable-cors.org/server_expressjs.html

**Comment by RIAEvangelist** [comment]
Hey thanks for the question.

For right now, use the ` server.beforeServe ` method to ` request.setHeader ` for this.

Your question though made me realise there should really be some default headers in the config. I will add this soon.

**Comment by RIAEvangelist** [comment]
updated the above.

**Comment by OlleMattsson** [comment]
Thank you! Exactly what was needed.

```
server.beforeServe = function (request,response,body,encoding){
    response.setHeader('Access-Control-Allow-Origin', 'http://<mydomain>');
    response.setHeader('Access-Control-Allow-Methods', 'OPTIONS, GET');
    response.setHeader('Access-Control-Allow-Headers', 'Authorization');
    response.setHeader('Access-Control-Allow-Credentials', 'true');
}
```

**Comment by RIAEvangelist** [comment]
:tada: :man_dancing:
