### ISSUE TITLE
Requesting large files (320 mb) causes 500 error

### ISSUE THREAD

**Issue by OlleMattsson** [RIAEvangelist/node-http-server#16]
When trying to GET a large file (320 mb video) the server derps out with the following error:

```
 Error: "toString()" failed
    at Buffer.toString (buffer.js:513:11)
    at tryToString (fs.js:421:15)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:412:12) 
```

Requesting smaller videos (~100 mb) does work. I haven't yet tested exactly at what point the break happens. I'll do some tests and report back.

Any ideas how to go about fixing something like this?

**Comment by RIAEvangelist** [comment]
Could be 2 things, corrupt data of some kind or file size. Please let me
know more about what you find.

Thanks
