### ISSUE TITLE
How to specify passphrase when using encrypted certificate

### ISSUE THREAD

**Issue by OlleMattsson** [RIAEvangelist/node-http-server#17]
EDIT: specified the question to be about passphrases (more helpful if someone else needs this)

When using a password protected private key, how do I go about specifying the password?

Config is as follows
```
config.https.privateKey = 'server.enc.key';
config.https.certificate= 'ssl_certificate.crt';
config.https.ca = 'intermediateCA.crt'
```

When server is run, output is
```
_tls_common.js:90
        c.context.setKey(options.key);
                  ^

Error: error:0906A068:PEM routines:PEM_do_header:bad password read
    at Object.createSecureContext (_tls_common.js:90:19)
    at Server (_tls_wrap.js:768:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:47:10)
    at Server.deploy (/home/codemate/node_modules/node-http-server/server/http.js:62:29)
    at Object.<anonymous> (/home/codemate/server.js:25:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by OlleMattsson** [comment]
Ok this was actually an easy fix:

In http.js: 
  added the `passphrase` line (lines 43 - 47)

```
this.config.httpsOptions = {
  key: fs.readFileSync(this.config.https.privateKey),
  cert: fs.readFileSync(this.config.https.certificate),
  passphrase: this.config.https.passphrase
};
```


server.js (config file):
```
config.https.privateKey = 'server.enc.key';
config.https.certificate= 'ssl_certificate.crt';
config.https.ca = 'intermediateCA.crt';
config.https.passphrase '< secret >';
```

The other parts of the config seems to have been in order =)

**Comment by RIAEvangelist** [comment]
Hey nice! Its a simple add, but you should get credit for it. Submit a PR and I'll merge it ;)

**Comment by RIAEvangelist** [comment]
easy fix, should add in. low hanging fruit for anyone that wants to submit a PR.

**Comment by RIAEvangelist** [comment]
added in version 7.0.0

**Comment by sajjad207** [comment]
so i dont have a https.js and my server.js file does not have any of the " config.https.privateKey = 'server.enc.key';
config.https.certificate= 'ssl_certificate.crt';
config.https.ca = 'intermediateCA.crt';
config.https.passphrase '< secret >';  "

**Comment by RIAEvangelist** [comment]
Are you sure you are using this lib, or maybe an older version?
