### ISSUE TITLE
HTTP Errors

### ISSUE THREAD

**Issue by CordEmpire** [RIAEvangelist/node-http-server#21]
Hi, I am new to Node.JS and HTTP, how would I go about changing the HTTP errors header and make them redirect or render an error page? Sorry, as I said I am new to this stuff.

**Comment by RIAEvangelist** [comment]
it would be in one of the on before events . you can bind a function to update the headers.

good luck!

**Comment by GhostlyDark** [comment]
A stupid way of doing this (modifying Config.js):

```
    errors:{
        headers : {
            'Content-Type' : 'text/html'
        },
        404: '<meta http-equiv="refresh" content="0; URL=404.htm">',
    }
```

This works, but a proper example would be much appreciated.

**Comment by CordEmpire** [comment]
Hi, thanks for the reply, I am at school right now so I cannot try but it looks like it will work. Cheers!

**Comment by CordEmpire** [comment]
Yes thank you this worked and sorry it taken a while to respond,.
